---
- name: Configure IP forwarding.
  lineinfile:
    dest: "{{ sys_ctl_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: "0640"
  with_items:
    - regexp: "^.*net.ipv4.ip_forward"
      line: "net.ipv4.ip_forward=1"
    - regexp: "^.*net.ipv6.conf.all.forwarding"
      line: "net.ipv6.conf.all.forwarding=1"

- name: Ensure sysctl IP forwarding is reloaded.
  command: sysctl -p
  changed_when: false
