---
- name: Enable IP forwarding (IPv4 + IPv6).
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
  with_items:
    - "net.ipv4.ip_forward"
    - "net.ipv6.conf.all.forwarding"
