---
- name: Download PiVPN script.
  get_url:
    url: "https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh"
    dest: "/tmp/install.sh"
    mode: "0600"

- name: Write variables to options.conf.
  template:
    src: "{{ playbook_dir }}/../templates/options.conf.j2"
    dest: /tmp/options.conf
    mode: "0600"

- name: Run install.sh with unattended flag.
  command: "/tmp/install.sh --unattended /tmp/options.conf"
  changed_when: false

- name: Cleanup installer files.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/install.sh"
    - "/tmp/options.conf"
