---
- name: Setup Pi VPN.
  hosts: all
  become: true

  vars_files:
    - "{{ playbook_dir }}/../default.config.yml"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/../config.yml"
      tags:
        - always

    - name: Update apt caches.
      package:
        update_cache: true
        cache_valid_time: 3600
      tags:
        - always

  handlers:
    - name: reload wg-portal
      systemd:
        name: wg-portal
        state: restarted

  tasks:
    - name: Install security services.
      include_role:
        name: rafael-c-alexandre.security
      vars:
        security_ansible_port: "{{ ssh_port }}"

    - name: Install NTP service.
      include_role:
        name: rafael-c-alexandre.ntp

    - include_tasks: "{{ playbook_dir }}/../tasks/{{ wireguard_installation_mode }}.yml"
      args:
        apply:
          tags:
            - wireguard
      tags:
        - wireguard
