---
- name: Install/update wg-portal.
  hosts: all
  become: true

  vars_files:
    - "{{ playbook_dir }}/../default.config.yml"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/../config.yml"

    - name: Update apt caches.
      package:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: reload wg-portal
      systemd:
        name: wg-portal
        state: restarted

  tasks:
    - name: Check if Wireguard is installed.
      stat:
        path: "{{ wireguard_conf_dir }}"
      register: wg_config

    - fail:
        msg: "Wireguard needs to be installed first."
      when: not wg_config.stat.exists

    - name: Set architecture fact.
      set_fact:
        arch: "{{ 'amd64' if ansible_facts.architecture == 'x86_64' else 'arm64' }}"

    - name: Download wg-portal.
      get_url:
        url: "https://github.com/h44z/wg-portal/releases/download/{{ wireguard_portal_version }}/wg-portal_linux_{{ arch }}"
        dest: "/tmp/wg-portal-{{ wireguard_portal_version }}"
        mode: "0750"

    - name: Create wg-portal directories.
      file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
      with_items:
        - "{{ wireguard_portal_binary_directory }}"
        - "{{ wireguard_portal_binary_directory }}/config"

    - name: Install wg-portal.
      command: "install /tmp/wg-portal-{{ wireguard_portal_version }} {{ wireguard_portal_binary_directory }}/wg-portal"
      changed_when: false

    - name: Allow traffic to wg-portal.
      ufw:
        rule: allow
        port: "{{ wireguard_portal_port }}"
        proto: tcp
        comment: "allow-wgportal"

    - name: Copy custom configuration and deploy systemd wg-portal service unit file.
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0640"
      with_items:
        - src: "{{ playbook_dir }}/../templates/wg-portal/wg-portal-config.yml.j2"
          dest: "{{ wireguard_portal_binary_directory }}/config/config.yml"
        - src: "{{ playbook_dir }}/../templates/wg-portal/wg-portal.service.j2"
          dest: /etc/systemd/system/wg-portal.service
      notify: reload wg-portal

    - name: Copy logrotate file for wg-portal log.
      template:
        src: "{{ playbook_dir }}/../templates/wg-portal/wg-portal.logrotate.log.j2"
        dest: "{{ wireguard_portal_logrotate_config_path }}"
        mode: "0640"

    - name: Reload systemd.
      systemd:
        daemon_reload: true

    - name: Start wg-portal service and enable at boot.
      systemd:
        name: wg-portal
        enabled: true
        state: started

# Missing:
# 4. Provide custom user and password.
# 5. Look into mail notifcation, TLS and certificates.
