---
'on':
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

env:
  TEST_CONFIGS_PATH: ./.github/configs

jobs:

  lint:
    name: Lint
    uses: rafael-c-alexandre/ansible-devops/.github/workflows/lint.yml@main
    with:
      lint_path: "./playbooks/"

  playbook-test:
    name: Run playbook test
    runs-on: ubuntu-22.04
    needs: lint
    strategy:
      matrix:
        wireguard_installation_mode: [vanilla_wireguard, pivpn]

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Setup necessary ssh keys for testing.
        run: |
          # SSH key necessary for initial SSH login.
          ssh-keygen -t rsa -b 4096 -f $TEST_CONFIGS_PATH/keys/ci -N ""
          # SSH key necessary for new ansible user.
          ssh-keygen -t rsa -b 4096 -f $TEST_CONFIGS_PATH/keys/ansible -N ""

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip3 install ansible
          sudo apt update

      - name: Setup SSH server.
        uses: rafael-c-alexandre/ansible-devops/.github/actions/start-ssh-server@main
        with:
          ssh_private_key_path: "$TEST_CONFIGS_PATH/keys/ci"
          ssh_public_key_path: "$TEST_CONFIGS_PATH/keys/ci.pub"

      - name: Download ansible roles.
        run: |
          cp $TEST_CONFIGS_PATH/ansible_pre_prepare.cfg ansible.cfg
          ansible-galaxy install -r requirements.yml

      - name: Fix ansible private keys permissions.
        run: chmod 600 $TEST_CONFIGS_PATH/keys/ci $TEST_CONFIGS_PATH/keys/ansible

      - name: Run prepare.yml playbook test.
        uses: rafael-c-alexandre/ansible-devops/.github/actions/playbook-test@main
        with:
          playbook_path: "./playbooks/prepare.yml"
          ansible_cfg_path: "$TEST_CONFIGS_PATH/ansible_pre_prepare.cfg"
          inventory_path: "$TEST_CONFIGS_PATH/inventory.ini"
          config_path: "$TEST_CONFIGS_PATH/config_pre_prepare.yml"

      - name: Run main.yml playbook test.
        uses: rafael-c-alexandre/ansible-devops/.github/actions/playbook-test@main
        with:
          playbook_path: "./playbooks/main.yml"
          ansible_cfg_path: "$TEST_CONFIGS_PATH/ansible_after_prepare.cfg"
          inventory_path: "$TEST_CONFIGS_PATH/inventory.ini"
          config_path: "$TEST_CONFIGS_PATH/config_after_prepare_${{ matrix.wireguard_installation_mode }}.yml"
